  spring:
    application:
      name: probate-orchestrator-service

  server:
    port: 8888

  management:
    endpoints:
      web:
        exposure:
          include: health,info
        base-path: /
    endpoint:
      health:
        show-details: always
        enabled: true

  authorised.services: probate_backend,probate_frontend

  auth.provider.service.client:
    baseUrl: http://localhost:4502
    microservice: 'probate_backend'
    key: 'AAAAAAAAAAAAAAAA'
    tokenTimeToLiveInSeconds: '900'

  idam.s2s-auth.url: ${auth.provider.service.client.baseUrl}

  service.auth.provider.base.url: ${auth.provider.service.client.baseUrl}

  auth.idam.client.baseUrl: http://localhost:4501

  s2s.auth.totp.secret: ${auth.provider.service.client.key}
  service.name: ${auth.provider.service.client.microservice}

  submit-service.api.url: http://localhost:8181
  business-service.api.url: http://localhost:8080

  logging:
  level:
    org.springframework.web: ERROR
    uk.gov.hmcts.probate: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
