tags:
  - idam-pr

java:
  applicationPort: 8888
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: orchestrator-service
    PACT_BROKER_URL: pact-broker.platform.hmcts.net
    PACT_BROKER_PORT: 80
  image: hmctspublic.azurecr.io/probate/orchestrator-service:latest
  keyVaults:
    "probate":
      resourceGroup: probate
      secrets:
        - s2sAuthTotpSecret
        - probateIdamSecret
        - probateIdamUserName
        - probateIdamPassword
        - probate-notify-invite-apikey
        - s2s-probate-backend
        - AppInsightsInstrumentationKey
        - probateCcdDataStoreApi
        - serviceAuthProviderBaseUrl
        - probateUserAuthUrl
        - probateIdamOauthRedirectUrl
        - probate-mail-host
        - probate-mail-username
        - probate-mail-password
        - probate-mail-port
        - probate-mail-sender
        - probate-mail-recipient
        - payCaseWorkerUser
        - payCaseWorkerPass
        - idamRedirectUrl
