tags:
  - idam-pr: false

java:
  applicationPort: 8888
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: orchestrator-service
    PACT_BROKER_URL: pact-broker.platform.hmcts.net
    PACT_BROKER_PORT: 80
  image: hmctspublic.azurecr.io/probate/orchestrator-service:latest
  aadIdentityName: probate
  keyVaults:
    "probate":
      resourceGroup: probate
      secrets:
        - AppInsightsInstrumentationKey
        - s2s-probate-backend
        - idamRedirectUrl
        - payCaseWorkerUser
        - payCaseWorkerPass
        - ccidam-idam-api-secrets-probate
        