tags:
  - idam-pr

java:
  applicationPort: 8888
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: orchestrator-service
    PACT_BROKER_URL: pact-broker.platform.hmcts.net
    PACT_BROKER_PORT: 80
  image: hmctspublic.azurecr.io/probate/orchestrator-service:latest