java:
  environment:
    SERVICES_PERSISTENCE_BASEURL : "http://probate-persistence-service-aat.service.core-compute-aat.internal"
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL : "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    SERVICES_CORECASEDATA_BASEURL : "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
    SERVICES_AUTH_PROVIDER_BASEURL : "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    AUTH_IDAM_CLIENT_BASEURL : "https://idam-api.aat.platform.hmcts.net"
    SUBMIT_SERVICE_API_URL : "http://probate-submit-service-pr-197.service.core-compute-preview.internal"
    BUSINESS_SERVICE_API_URL : "http://probate-business-service-aat.service.core-compute-aat.internal"
    BACK_OFFICE_API_URL: "http://probate-back-office-aat.service.core-compute-aat.internal"
    SERVICES_AUTH_PROVIDER_TOTP_SECRET: ${S2S_AUTH_TOTP_SECRET}
    LOG_LEVEL: DEBUG
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_SSL_ENABLE: false
    MAIL_JAVAMAILPROPERTIES_MAIL_SMTP_AUTH: false
    SERVICES_CORECASEDATA_ENABLED: true
    MAIL_JAVAMAILPROPERTIES_SUBJECT: Probate Application
    AUTH_PROVIDER_SERVICE_CLIENT_KEY: ${S2S_AUTH_TOTP_SECRET}
    MAIL_USERNAME: ${PROBATE_SUB_MAIL_USERNAME}
    MAIL_PASSWORD: ${PROBATE_SUB_MAIL_PASSWORD}
    MAIL_HOST: ${PROBATE_SUB_MAIL_HOST}
    MAIL_PORT: ${PROBATE_SUB_MAIL_PORT}
    MAIL_JAVAMAILPROPERTIES_SENDER: ${PROBATE_SUB_MAIL_SENDER}
    MAIL_JAVAMAILPROPERTIES_RECIPIENT: ${PROBATE_SUB_MAIL_REC}
    IDAM_API_REDIRECT_URL: ${IDAM_REDIRECT_URL}
    AUTH2_CLIENT_SECRET: ${IDAM_SECRET}
    PAYMENT_CASEWORKER_USERNAME: ${PAYMENT_CASEWORKER_USERNAME}
    PAYMENT_CASEWORKER_PASSWORD:  ${PAYMENT_CASEWORKER_PASSWORD}
  ingressHost: ${SERVICE_FQDN}

idam-pr:
  redirect_uris:
    Probate:
      - https://${SERVICE_FQDN}/oauth2/callback
